### ISSUE TITLE
question

### ISSUE THREAD

**Issue by vitaly-t** [Innovu/glider#1]
Did you find something missing within [pg-promise](https://github.com/vitaly-t/pg-promise) that you decided  to write one of your own? Or is it just an exercise project? :)

I wonder, because I am always open to ideas of how to improve the library further.

Cheers!

**Comment by tonylukasavage** [comment]
@vitaly-t there were 3 reasons I started writing this:
1. We were starting to incrementally grow a module that did this internally for our purposes and it made sense to break out some of the functionality we were building.
2. My focus with `glider` was to be "simple and expressive" for querying, not to solve all of the possible postgres problems you might encounter. It's core principle is a bit opposite, in a sense, to pg-promise which describes itself as an "advanced access layer". This is reaffirmed by the mountain of documentation. And don't take that as an knock in any way, the docs are great. I'm just looking to do less with `glider`.
3. Most importantly, though, the manner in which `glider` deviates from `pg-promise` most is the API. While any API call in glider will return a Promise (like pg-promise), the real value is in the expressive chaining of a series of queries (and eventually parallel as well) which collects all the results and automatically handles all connections and transactions. This to me felt like a fairly serious deviation from pg-promise's API and I was very skeptical that anything so different would be pulled into pg-promise. 

So that's the rationale. Basically glider is smaller, and more focused on simple, expressive querying without having to know a damn thing about transactions, connection pooling, etc... 

I'd be happy to talk more about it if you don't see the difference as being so distinct. Or if that does make sense, let me know. Thanks for dropping in to lend your opinion. Just out of curiosity, how the heck did you find the repo? I didn't even release a version or publish to npm yet.

**Comment by vitaly-t** [comment]
> Just out of curiosity, how the heck did you find the repo? I didn't even release a version or publish to npm yet.

GitHub search engine allows you to see all the recent additions that either use or mention your library (pg-promise in this case).

> expressive querying without having to know a damn thing about transactions, connection pooling, etc...

This is what pg-promise does, it hides all that complexity from you :) You don't need to know any of that to write your code, and [Learn By Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) tutorial shows you how to do that.

> This is reaffirmed by the mountain of documentation

Good documentation doesn't imply complexity. I spent a lot of time writing it, to make the use of this library as clear as possible, from the myriad of examples provided. For example, have you seen this - [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo)?

I believe the best way to understand something is from a practical example, and if you have a case in point, I can explain how to implement it, if it is not clear.

By the way, pg-promise has the best support for automatic transactions. Re-implementing it would be very complex, especially considering nested transactions and transaction configurations.

**Comment by tonylukasavage** [comment]
> Good documentation doesn't imply complexity

I never said it did and actually complimented your docs.

> This is what pg-promise does...

Did you look at how distinctly different our APIs are though? I get that we're both "hiding complexity", but it seems we're doing it is very different ways. In pg-promise's case through pure Promise chaining, in glider's through a specialized chaining API that makes the code as terse and expressive as possible. Rather than thinking of this as "why is he bothering, pg-promise is already a good API" (which I don't dispute), I'm taking a slightly different approach in the API presented, more like somewhere between pg-promise and [pg-bricks](https://github.com/Suor/pg-bricks). I feel like you're skating past the point that our APIs are a different way of approaching the querying problem, which is the **_sole_** focus of glider. 

> I believe the best way to understand something is from a practical example, and if you have a case in point, I can explain how to implement it, if it is not clear.

There's nothing unclear per sé about pg-promise, only that the API I'm presenting, IMO and my team's, is more expressive and readable than a Promise chain for **_our_** purposes. pg-promise, and the demo you showed, are a fantastic example of implementing a straight up REST API back by postgres with single queries. In our system (and I'm sure many others) we are doing complex, interdependent queries that often need to run in series, either due to necessity or that our data team is our bottleneck and we need to allow devs to solve SQL problems as best they can via multiple queries. This doesn't imply that pg-promise doesn't handle multiple queries well, only that we prefer glider's API for it to pg-promise's.

> By the way, pg-promise has the best support for automatic transactions. Re-implementing it would be very complex, especially considering nested transactions and transaction configurations.

...and if nested transactions and transaction configurations are something a developer needs, pg-promise is the better choice. 

Finally, though, I just want to make sure you see the difference between our APIs and why I think there's a distinction. I think this is the point we aren't seeing eye to eye on. I'm interested in your opinion because I think there is a distinct difference, and in that case, there's basically 2 plans of action:
1. continue developing glider
2. work with you to integrate the API in pg-promise

If you see the distinction, and if #2 isn't satisfactory to you, I'm assuming you'd no longer have a problem with #1, right?

**Comment by tonylukasavage** [comment]
@vitaly-t Having said all that, given how steadfast you are here, I may spend a little more time with pg-promise along with something like the `co` module to get it to act a bit more like `glider`'s API. It's a trade-off, right? I can use pg-promise and get a slightly less terse, readable chain of queries, but I'll be ready for async/await if and when it lands in JS and subsequently node.js. I fear that period of time will be measured in years though, at least in making it all the way to v8/node.js

**PS** - No, I do not want to use a transpiler on my code for the sake of async/await.

**Comment by vitaly-t** [comment]
pg-pormise already has a decent support for ES6 generators, which allows writing very clean code as tasks and transactions. See [Generators](https://github.com/vitaly-t/pg-promise#generators), [Tasks](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks).

**Comment by tonylukasavage** [comment]
Yeah, I see those, and they are good but not quite, IMO, as terse/expressive as glider. Rather than speaking in hypotheticals then, and in the absence of any comment so far by you on glider's actual API distinction from pg-promise, I'll throw this out there...

Here's an example from the README of glider:

``` js
var db = glider(CONNECTION_STRING);
db
    .begin()
    .query('create table foo (id serial, value integer)')
    .insert('insert into foo (value) values ($1), ($2), ($3)', [1, 2, 3])
    .update('update foo set value = 99 where id = 1')
    .delete('delete from foo where id = 3')
    .select('select * from foo')
    .selectOne('select value from foo where id = 1')
    .selectValue('select value from foo where id = 1')
    .commit()
    .then(function(results) {
        console.log(results[0].command); // CREATE
        console.log(results[1]);         // 3
        console.log(results[2]);         // 1
        console.log(results[3]);         // 1
        console.log(results[4]);         // [ { id: 1, value: 99 }, { id: 2, value: 2 } ]
        console.log(results[5]);         // { id: 1, value: 99 }
        console.log(results[6]);         // 99
    });
```

What is the pg-promise equivalent of this case? Bear in mind the following criteria, which were the driving force behind creating glider, none of which I want to sacrifice. I know pg-promise hits a lot of these, but a few are why I made glider's API (particularly the 3rd and 4th point), but I'd be happy to be proven wrong and adopt pg-promise if I'm just missing something.
1. Transactions are braindead simple, and I'm not concerned about nested ones
2. There's no connection handling, all under the hood
3. There are **NO** intermediate Promises to handle. glider's unique chaining allows me to operate using promises without intermediate promises, generator functions, or specially crafted function signatures that jive with the unique result of the prior query.
4. There is almost nothing but glider API function and query string, nothing else to consider in this chaining, making it extremely easy to follow.
5. Access to all results set in a final promise
6. Automatic ROLLBACK handling on transactions

**Comment by vitaly-t** [comment]
pg-promise uses the result approach to method names, so normally you expect results only according to the method names, like this:

``` js
var db = pgp(CONNECTION_STRING);
db.tx(t=>
        t.batch([
            t.none('create table foo (id serial, value integer)'),
            t.none('insert into foo (value) values ($1), ($2), ($3)', [1, 2, 3]),
            t.none('update foo set value = 99 where id = 1'),
            t.none('delete from foo where id = 3'),
            t.any('select * from foo'),
            t.one('select value from foo where id = 1'),
            t.one('select value from foo where id = 1')
        ]))
    .then(function (results) {
        // result[0] - result[3] = undefined;
        // result[4] = [ { id: 1, value: 99 }, { id: 2, value: 2 } ]
        // result[5] = { id: 1, value: 99 }
        // result[6] = { id: 1, value: 99 }
    });
```

But if you do not want queries to return values and what to access the affected rows count, then you can:

``` js
db.tx(t=>
        t.batch([
            t.none('create table foo (id serial, value integer)'),
            t.result('insert into foo (value) values ($1), ($2), ($3)', [1, 2, 3]).then(r=>r.rowCount),
            t.result('update foo set value = 99 where id = 1').then(r=>r.rowCount),
            t.result('delete from foo where id = 3').then(r=>r.rowCount),
            t.any('select * from foo'),
            t.one('select value from foo where id = 1'),
            t.one('select value from foo where id = 1')
        ]))
    .then(function (results) {
        // result[0] = undefined;
        // result[1] = 3
        // result[2] = 1
        // result[3] = 1
        // result[4] = [ { id: 1, value: 99 }, { id: 2, value: 2 } ]
        // result[5] = { id: 1, value: 99 }
        // result[6] = { id: 1, value: 99 }
    });
```

**Comment by tonylukasavage** [comment]
I thought that was essentially how it was laid out. Thank you for translating the example to pg-promise. I appreciate your interaction here.

As you might imagine, I'm still preferring the glider API. I also have a number of improvements I'm planning that might elucidate for you further how the focus in glider is different than pg-promise. The best analogy I can think of off the top of my head is that glider aims to be a pair of tweezers, and pg-promise seems like the swiss army knife that has tweezers in it. If I'm a person that just wants tweezers, just give me glider. If I also want a knife or a nail file too, then pg-promise is always more appropriate. 

If you'd like to discuss further, let's move this to email since this is more an author-to-author discussion at this point: anthony.lukasavage@gmail.com
